### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by misiek08** [tpiros/simple-chat#3]
I don't know why you didn't put everything into single server, but anyway you put some crazy characters into code and it fails marvelously tragically. Not a good example for beginners :(

**Comment by tpiros** [comment]
@misiek08 the crazy characters are a byproduct of a copy-paste that I have done for reasons that I can't recall. This is one of the most simple examples out there. This was also one of my first projects when I was learning this technology. I do apologise if it doesn't suit your needs.

**Comment by arnonuem** [comment]
@misiek08 just replace all backticks and doublel backticks with double quotes and the app works again.

**Comment by misiek08** [comment]
@arnonuem I know and I did it at sight. Just it made me crazy to see such thing in code...
